# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: josh becker blogs about code
email: joshua@becker.codes
description: > # this means to ignore newlines until "baseurl:"
  My name is Josh Becker and this is my blog about programming and getting better at it.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://becker.codes" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  JoshuaStorm

# Build settings
markdown: kramdown
